# Generated by Django 4.0.4 on 2022-06-09 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnvisaNome',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nomeproduto', models.CharField(blank=True, db_column='nomeProduto', max_length=250, null=True)),
            ],
            options={
                'db_table': 'anvisa_nome',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AnvisaPrincipioativo',
            fields=[
                ('id_pativo', models.IntegerField(db_column='id_pAtivo', primary_key=True, serialize=False)),
                ('nome_pativo', models.CharField(blank=True, db_column='nome_pAtivo', max_length=250, null=True)),
                ('translated_pativo', models.CharField(blank=True, db_column='translated_pAtivo', max_length=250, null=True)),
            ],
            options={
                'db_table': 'anvisa_principioativo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BigtableNomes',
            fields=[
                ('id_principal', models.IntegerField(blank=True, primary_key=True)),
                ('nome', models.CharField(blank=True, max_length=250, null=True)),
                ('tipo_origem', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bigtable_nomes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DrugbankNome',
            fields=[
                ('drugbank_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'drugbank_nome',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AnvisaNomePrincipioativo',
            fields=[
                ('idproduto', models.OneToOneField(db_column='idProduto', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='paracetamal.anvisanome')),
            ],
            options={
                'db_table': 'anvisa_nome_principioativo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DrugbankAnvisa',
            fields=[
                ('drugbank', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='paracetamal.drugbanknome')),
                ('matchingvalue', models.FloatField(blank=True, db_column='matchingValue', null=True)),
            ],
            options={
                'db_table': 'drugbank_anvisa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DrugbankInteracao',
            fields=[
                ('drugbank_id1', models.OneToOneField(db_column='drugbank_id1', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='drugbank_id1', serialize=False, to='paracetamal.drugbanknome')),
            ],
            options={
                'db_table': 'drugbank_interacao',
                'managed': False,
            },
        ),
    ]
