# Generated by Django 4.0.4 on 2022-04-22 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paracetamal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bigtablenomes',
            name='id',
        ),
        migrations.AlterField(
            model_name='bigtablenomes',
            name='id_principal',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
